feat(server): decrement placed quantities on order canceled
LAZONEDEV/medusa-product-availability-plugin pull request #129
Opened 2024-08-27 13:56 UTC by BOCOVO

Decrement placed quantities on availability product when an order is canceled.

[screen-capture (43).webm](https://github.com/user-attachments/assets/8833b9b9-631e-4aaa-8101-f1c08f96a353)

2024-09-02 20:22 UTC, Valentino-Houessou requested changes
typo suggestions

2024-09-02 20:22 UTC, Valentino-Houessou commented on src/services/availability.ts
> +  async handleRollbackPlacedQuantities(em: EntityManager, orderID: string) {
```suggestion
  async rollbackPlacedQuantities(em: EntityManager, orderID: string) {
```

2024-09-03 06:01 UTC, BOCOVO commented on src/subscribers/decrement-placed-qty.ts
> +  const orderService: AvailabilityService = container.resolve(
bien vu @Valentino-Houessou

2024-09-09 13:10 UTC, BOCOVO commented
@Valentino-Houessou 
tu peux repasser ici stp ?

2024-09-09 13:16 UTC, Valentino-Houessou approved these changes

2024-09-09 20:18 UTC, merged